### ISSUE TITLE
Different recording lengths, sample rates and vigilance states

### ISSUE THREAD

**Issue by rjp109** [paulbrodersen/somnotate#11]
Hello,

I have been trying to get somnotate running on my mouse EEG data but have run into several issues.

1. When running '02_test_state_annotation.py', it seems to have an issue when my edfs are of different lengths. I typically record for different amounts of time for different animals so truncating all to the same length is not an option. Can you please help with a solution for this? Error below:

`Loading data sets..
.C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/3)
C:\Users\rp17047\somnotate\somnotate\_utils.py:145: UserWarning: Interval values are converted from floats to integers.
  warnings.warn("Interval values are converted from floats to integers.")
C:\Users\rp17047\22qScore\processed\148140_301123.npy (2/3)
C:\Users\rp17047\22qScore\processed\148144_281123.npy (3/3)
Testing...
C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py:94: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  unique_states = np.unique(np.abs(state_vectors))
Traceback (most recent call last):
  File "C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py", line 94, in <module>
    unique_states = np.unique(np.abs(state_vectors))
  File "<__array_function__ internals>", line 180, in unique
  File "C:\Users\rp17047\AppData\Local\miniconda3\envs\somnotate_env\lib\site-packages\numpy\lib\arraysetops.py", line 274, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts,
  File "C:\Users\rp17047\AppData\Local\miniconda3\envs\somnotate_env\lib\site-packages\numpy\lib\arraysetops.py", line 336, in _unique1d
    ar.sort()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

2. I have 4 vigilance states i want to score - wake, nrem, rem and artefact (any stage). I have modified these in the configuration file but i am getting the following error when running '02_test_state_annotation.py' . 

`Loading data sets...
C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/2)
C:\Users\rp17047\somnotate\somnotate\_utils.py:145: UserWarning: Interval values are converted from floats to integers.
  warnings.warn("Interval values are converted from floats to integers.")
C:\Users\rp17047\22qScore\processed\148140_301123.npy (2/2)
Testing...
C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/2) accuracy : 91.5%
Traceback (most recent call last):
  File "C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py", line 114, in <module>
    confusion[ii] = get_confusion_matrix(np.abs(state_vectors[ii]), annotator.predict(signal_arrays[ii]), labels=unique_states)
ValueError: could not broadcast input array from shape (3,3) into shape (4,4)
(somnotate_env) C:\Users\rp17047\somnotate>
(somnotate_env) C:\Users\rp17047\somnotate>python C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py C:\Users\rp17047\22qScore\TrainingSetshort.csv
Loading data sets...
C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/2)
C:\Users\rp17047\somnotate\somnotate\_utils.py:145: UserWarning: Interval values are converted from floats to integers.
  warnings.warn("Interval values are converted from floats to integers.")
C:\Users\rp17047\22qScore\processed\148140_301123.npy (2/2)
Testing...
C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/2) accuracy : 91.5%
Traceback (most recent call last):
  File "C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py", line 114, in <module>
    confusion[ii] = get_confusion_matrix(np.abs(state_vectors[ii]), annotator.predict(signal_arrays[ii]), labels=unique_states)
ValueError: could not broadcast input array from shape (3,3) into shape (4,4)`

I have modified the configuration file as follows, i did try leaving in the unused variables, but it did not help
`state_to_int = dict([`
`    ('Wake'               ,  1),`
`    ('Art'                , -1),`
` #  ('sleep movement'     ,  1),`
`    ('N2'                 ,  2),`
`  #  ('non-REM (artefact)' , -2),`
`    ('REM'                ,  3),`
 `  # ('REM (artefact)'     , -3),`
`    ('undefined'          ,  0),
])`

`# Construct the inverse mapping to convert back from state predictions to human readabe labels.
int_to_state = {ii : state for state, ii in state_to_int.items() if state != 'sleep movement'}`

`# define the keymap used for the manual annotation`
`keymap = {
    'w' : 'Wake',
    'W' : 'Art',
    'n' : 'N2',`
`   # 'N' : 'non-REM (artefact)',`
`    'r' : 'REM',`
`   # 'R' : 'REM (artefact)',`
`    'x' : 'undefined',`
` #   'X' : 'undefined (artefact)',`
`  #  'm' : 'sleep movement',`
` #   'M' : 'sleep movement (artefact)',
}`

`# define the visual display of states`
`state_to_color = {`
`    'Wake'                : 'crimson',`
`    'Art'                 : 'coral',`
` #   'sleep movement'      : 'violet',`
`    'N2'                  : 'blue',`
`   # 'non-REM (artefact)'  : 'cornflowerblue',`
`    'REM'                 : 'gold',`
`    #'REM (artefact)'      : 'yellow',`
` #   'sleep movement'      : 'purple',`
`    'undefined'           : 'gray',`
`  #  'undefined (artefact)': 'lightgray',`
`}`

`state_display_order = [
    'Wake',
    'Art',
    'N2',`
`   # 'non-REM (artefact)',`
`    'REM',`
`   # 'REM (artefact)',`
`  #  'sleep movement',`
`  #  'sleep movement (artefact)',`
`    'undefined',`
`  #  'undefined (artefact)',`
`]`  

3. I seemed to have solved this one, but when running '01_preprocess_signals.py' it doesn't seem to work with a sample rate other than 256Hz (I'm using 250Hz) since it seems to be importing the sample rate as a float rather than int. I managed to solve this by adding the following after line 134:
`datasets['sampling_frequency_in_hz']=datasets['sampling_frequency_in_hz'].astype(int)`

`Traceback (most recent call last):
  File "C:\Users\rp17047\somnotate\example_pipeline\01_preprocess_signals.py", line 167, in <module>
    time, frequencies, preprocessed_signal = preprocess(signal, dataset['sampling_frequency_in_hz'],
  File "C:\Users\rp17047\somnotate\example_pipeline\01_preprocess_signals.py", line 84, in preprocess
    frequencies, time, spectrogram = get_spectrogram(raw_signal,
  File "C:\Users\rp17047\AppData\Local\miniconda3\envs\somnotate_env\lib\site-packages\lspopt\lsp.py", line 145, in spectrogram_lspopt
    H, taper_weights = lspopt(n=nperseg, c_parameter=c_parameter)
  File "C:\Users\rp17047\AppData\Local\miniconda3\envs\somnotate_env\lib\site-packages\lspopt\lsp.py", line 56, in lspopt
    h = np.vstack((np.ones((n,)), 2 * t1))
  File "C:\Users\rp17047\AppData\Local\miniconda3\envs\somnotate_env\lib\site-packages\numpy\core\numeric.py", line 191, in ones
    a = empty(shape, dtype, order)
TypeError: 'float' object cannot be interpreted as an integer`

**Comment by paulbrodersen** [comment]
Hi, thanks for raising the issues. Could you do me a favour and raise three separate issues, one for each bullet point? Then it's easier to keep track of what has been addressed and what hasn't. Thanks!
