### ISSUE TITLE
Recordings of different lengths

### ISSUE THREAD

**Issue by rjp109** [paulbrodersen/somnotate#12]
When running '02_test_state_annotation.py', it seems to have an issue when my edfs are of different lengths. I typically record for different amounts of time for different animals so truncating all to the same length is not an option. Can you please help with a solution for this? Error below:

`Loading data sets.. .C:\Users\rp17047\22qScore\processed\148139_301123.npy (1/3) C:\Users\rp17047\somnotate\somnotate\_utils.py:145: UserWarning: Interval values are converted from floats to integers. warnings.warn("Interval values are converted from floats to integers.") C:\Users\rp17047\22qScore\processed\148140_301123.npy (2/3) C:\Users\rp17047\22qScore\processed\148144_281123.npy (3/3) Testing... C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py:94: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray. unique_states = np.unique(np.abs(state_vectors)) Traceback (most recent call last): File "C:\Users\rp17047\somnotate\example_pipeline\02_test_state_annotation.py", line 94, in <module> unique_states = np.unique(np.abs(state_vectors)) File "<__array_function__ internals>", line 180, in unique File "C:\Users\rp17047\AppData\Local\miniconda3\envs\somnotate_env\lib\site-packages\numpy\lib\arraysetops.py", line 274, in unique ret = _unique1d(ar, return_index, return_inverse, return_counts, File "C:\Users\rp17047\AppData\Local\miniconda3\envs\somnotate_env\lib\site-packages\numpy\lib\arraysetops.py", line 336, in _unique1d ar.sort() ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by paulbrodersen** [comment]
This issue should have been addressed in a previous commit a while back. Are you using the latest version?

**Comment by rjp109** [comment]
Hello, yes I am, I only downloaded a couple of days ago. 
I tried running this on two recordings of the same length and it was fine, but when I added two more recordings of different lengths to the first two I got this error

**Comment by paulbrodersen** [comment]
Alright, I will look into what happened there.

**Comment by paulbrodersen** [comment]
Could you install the latest version from source and test if this fixes this issue?

**Comment by rjp109** [comment]
This seems to have fixed the issue, thank you!
