### ISSUE TITLE
state likelihood output

### ISSUE THREAD

**Issue by rjp109** [paulbrodersen/somnotate#15]
Hi again, sorry for posting multiple issues! I am a bit confused with the outputs I'm getting from somnotate - i have an 'intervals.hyp' file to which i assume the score it provides is the likelihood of each state scored - however it does not say within this spreadsheet which state that was. This also does not correspond clearly with the 'automated_state_annotation.hyp' file to match up which state it is referrring to. Am I missing a step?

Another thing, I assumed this score is a probabiltiy up to 1, but many of the values I am getting are above 1 - unless it is actually a percentage up to 100 - but if so, the majority of my scores are below 10 and so i guess it hasn't worked so well.

**Comment by rjp109** [comment]
Okay great, thank you for the explanation. So how do you get an output of the state likelihoods?
I'm getting more errors with the manual refinement script, will post a new issue on that.

**Comment by paulbrodersen** [comment]
None of the scripts currently export the likelihoods of the predicted state or the likelihoods of all states, but it should not be too hard to extract them.

1. If you want access the likelihood of the predicted state, then the easiest solution is to manipulate the `04_run_state_annotation.py`. 

Ll. 120: 
```python 
# compute intervals for manual review
state_probability = annotator.predict_proba(signal_array)
export_intervals_with_state_probability_below_threshold(dataset['file_path_review_intervals'],
                                                               state_probability,
                                                               threshold=0.99)
# TODO
# np.save("/path/to/file.npy", state_probability)
```

2. If you want to access the likelihood of all states, then have a look at the `StateAnnotator` class in somnotate/_automated_state_annotation.py, specifically its `predict_proba` method. You will probably want to add another, simpler method that returns all probabilities. 

```python 

class MyCustomStateAnnotator(StateAnnotator):
    def predict_all_probabilities(self, signal_array):
        self._check_signal_array(signal_array)
        transformed_array = self.transform(signal_array)
        probability_array = self.hmm.predict_proba([sample for sample in transformed_array])
        return probability_array
       
```

**Comment by rjp109** [comment]
Okay great thank you, I have managed to extract for all states, very useful!

**Comment by paulbrodersen** [comment]
I have added another script to `example_pipeline`, namely `07_compute_state_probabilities.py`. 
This script requires another column in the the spreadsheet with the name: `file_path_state_probabilities`.
The entries in this column should follow the format `/path/to/desired/filename.npz`.
The resulting NPZ files can then be loaded with numpy: 

```python
import numpy as np
state_probabilities = np.load("/path/to/filename.npz")
print(state_probabilities["awake"])
# array([1.62583559e-04, 8.15282032e-07, 1.29982648e-06, ...,
#       8.14312684e-08, 3.57478011e-07, 5.01583361e-05])
```
