### ISSUE TITLE
Read file problems

### ISSUE THREAD

**Issue by A-Fisk** [paulbrodersen/somnotate#2]
Two issues I've found so far, no idea best way to fix them at the moment but recording here. 

1. In 00_convert_sleepsign_files.py, I've written my sleepsign file outputs slightly differently as a csv rather than tab delineated. Might be missing how to pass the `*kwarg` from the terminal but I had to modify the script to include `deliminator="."` to get it to read the files correctly.
2. I've written my EDF files to continue until the data runs out, rather than being strictly 24 hours. Therefore I kept on running into problems in 03_train_state_annotations.py with it complaining the dimension is >86400. I solved this by manually going into 01_preprocess_signals.py and altering it like this.

old 

    for signal in raw_signals.T:
                time, frequencies, preprocessed_signal = preprocess(signal, 
                                                                    dataset['sampling_frequency_in_hz'],
                                                                    time_resolution_in_sec   = time_resolution,
                                                                    low_cut                  = 1.,
                                                                    high_cut                 = 90.,
                                                                    notch_low_cut            = 45.,
                                                                    notch_high_cut           = 55.,
                )
                preprocessed_signals.append(preprocessed_signal)

to new 

    for signal in raw_signals.T:
                time, frequencies, preprocessed_signal = preprocess(signal, 
                                                                    dataset['sampling_frequency_in_hz'],
                                                                    time_resolution_in_sec   = time_resolution,
                                                                    low_cut                  = 1.,
                                                                    high_cut                 = 90.,
                                                                    notch_low_cut            = 45.,
                                                                    notch_high_cut           = 55.,
                )
               
                preprocessed_signal = preprocessed_signal[:, :86400]
                preprocessed_signals.append(preprocessed_signal)

**Comment by paulbrodersen** [comment]
Regarding 2: 

In my opinion, having any functionality that handles non-commensurate array dimensions "behind the scenes" is very dangerous and can lead to bugs that are very hard to find. Imagine that you specified the sampling frequency wrongly, in particular too low. Then the preprocessing would result in more samples than seconds annotated; however, cutting the preprocessed array and the annotations to the same length would -- in turn -- make the array sizes commensurate again, hiding the misalignment and potentially wrecking everything downstream. Throwing an error here is a feature, IMO, not a bug.   

However, maybe we should include a recipe on how to trim EDF files to the correct size (which is not hard with pyedflib). 

---

Regarding 1:

I planned to implement functionality that would allow keyword argument pass-through but then didn't to keep the code complexity manageable. As is, it uses any whitespace (not just tabs) to delineate fields. Is that not the default export format for the sleepsign FFT files? 

I don't want to support every export format of sleepsign, especially as that might be subject to change.
