### ISSUE TITLE
Using 1 eeg channel for automatic scoring when model is trained with 2 eeg channels

### ISSUE THREAD

**Issue by vlkuzun** [paulbrodersen/somnotate#20]
Hi, we are currently using this repo to automate our vigilance states in mice and although the model was trained with 2 EEG channels in some recordings we only have 1 working EEG channel. When attempting to score with 1 EEG channel it is throwing an error when running `04_run_state_annotation.py` of `ValueError: X has 156 features, but LinearDiscriminantAnalysis is expecting 234 features as input.`

Is there a way we could still complete the scoring with 1 EEG channel without retraining the model?

Thanks in advance!

**Comment by paulbrodersen** [comment]
No, that isn't possible. However, if your annotated training data has two channels, then it should be pretty easy to train a second model with just one of the channels.

**Comment by vlkuzun** [comment]
Great, thanks!

**Comment by paulbrodersen** [comment]
For completeness sake: the only thing you should need to adjust are a few variables in the `configuration.py` file, specifically the variables `state_annotation_signals` (important), `state_annotation_signal_labels` & `state_annotation_signal_frequency_bands` (just for plotting). Then re-run the processing, testing, and training, and apply the resulting single-channel model to your files missing a channel.
