### ISSUE TITLE
"List index out of range" error with --only parameter if numbers are skipped in the list of files

### ISSUE THREAD

**Issue by otoien** [paulbrodersen/somnotate#9]
Gaps in the sequence of --only parameters will cause a "list index out of range" error.  Let test1.csv be a list with 6 valid entry rows. (In the example below I am leaving out the full paths used.) 
02_test_state_annotation.py Beartest1n.csv" --only 0 1 2 3 4 5  or
02_test_state_annotation.py Beartest1n.csv" --only 0 1 2  executes without errors.
However 
02_test_state_annotation.py Beartest1n.csv" --only 0 1 3 4 5  or
02_test_state_annotation.py Beartest1n.csv" --only 0  2  executes with error on the first file pointed to by the index after the gap or the one after it :
```
Traceback (most recent call last):
  File "C:\somnotate\example_pipeline\02_test_state_annotation.py", line 116, in <module>
    accuracy[ii] = annotator.score(signal_arrays[ii], np.abs(state_vectors[ii]))
IndexError: list index out of range
```
I am not sure if this is a limitation or a bug. It is not important to me as I prefer to create dedicated .csv files, so I do not intend to work on it. It looks like the index used is the index of the row in the file while it should have the one counted by the number of indexes in the only parameter, or vice versa.

**Comment by paulbrodersen** [comment]
The issue stemmed from the fact that the index returned by `pandas.DataFrame.iterrows` is the index of the corresponding row in the dataframe, not a generic enumerator. With the `--only` flag, this index could be larger than the number of datasets and hence the dimensions of the pre-initialised `accuracy` vector. This issue should be resolved now.
